felleslosninger/github-workflows

.github/js/base64-utils.js
.github/js/github-context-utils.js
.github/js/influxdb-client.js
.github/js/octokit.js
.github/js/release-notes.js
.github/js/utils.js

PF-976-add-missing-js

---

.github/workflows/misc-approve-and-merge-pr.yml

New shared workflow to help automate approval and merging og PRs

Adds new misc-approve-and-merge-pr workflow

---

.github/workflows/misc-approve-and-merge-dependabot-pr.yml

Det er et script som skal brukes for å godkjenne og merge dependabot endringer automatisk

KRR-508 Legge til auto-merge script i github-workflows

---

.github/workflows/misc-approve-and-merge-dependabot-pr.yml

For results see here https://github.com/felleslosninger/plattform-test-app/actions/runs/7423259219

Improve summary for failed dependabot auto merge

---

.github/workflows/update-image-version.yml

Test run https://github.com/felleslosninger/plattform-test-app/actions/runs/7499737801

Removes usage of EID_PLATFORM_PAT

---

.github/workflows/misc-approve-and-merge-dependabot-pr.yml

Adds output for merged status

---

.github/workflows/ci-quarkus-build-publish-image.yml
.github/workflows/ci-quarkus-container-scan.yml
.github/workflows/ci-quarkus-native-build-publish-image.yml
.github/workflows/ci-spring-boot-build-publish-image.yml

ID-3805: Legg til github workflows for quarkus build/publish/container-scan

ID-3805: Legg til github workflows for quarkus build/publish/container-scan

---

.github/workflows/ci-quarkus-container-scan.yml
.github/workflows/ci-quarkus-native-build-publish-image.yml

ID-3805: justere buildpacks uri

ID-3805: justere buildpacks uri

---

.github/workflows/ci-quarkus-container-scan.yml
.github/workflows/ci-quarkus-native-build-publish-image.yml

ID-3805: legg til full url på buildpacks

ID-3805: legg til full url på buildpacks

---

.github/workflows/ci-quarkus-build-publish-image.yml
.github/workflows/ci-quarkus-container-scan.yml
.github/workflows/ci-quarkus-native-build-publish-image.yml

ID-3805: gjer m2 cache rw

---

.github/workflows/ci-quarkus-build-publish-image.yml
.github/workflows/ci-quarkus-container-scan.yml
.github/workflows/ci-quarkus-native-build-publish-image.yml
.github/workflows/ci-spring-boot-build-publish-image.yml
.github/workflows/ci-spring-boot-container-scan.yml
.github/workflows/test-k6-build-docker.yml
.github/workflows/test-k6-build-publish-docker.yml

Reverts felleslosninger/github-workflows#47

Revert "Bump aquasecurity/trivy-action from 0.16.1 to 0.17.0"

---

.github/workflows/ci-check-for-cve-suppression-changes.yml

Reusable workflow for sjekk av suppressed eller un-suppressed CVE endringer i filen .trivyignore.

Add CVE suppression changes workflow

---

.github/workflows/ci-update-image-version.yml

Reverts felleslosninger/github-workflows#76

Revert "Adds kubernetes-repo to client payload for update image"

---

.github/workflows/ci-docker-build-publish-image.yml
.github/workflows/ci-quarkus-build-publish-image.yml
.github/workflows/ci-quarkus-container-scan.yml
.github/workflows/ci-quarkus-native-build-publish-image.yml
.github/workflows/ci-spring-boot-build-publish-image.yml
.github/workflows/ci-spring-boot-container-scan.yml
.github/workflows/test-k6-build-docker.yml
.github/workflows/test-k6-build-publish-docker.yml

Reverts felleslosninger/github-workflows#106

Revert "Bump aquasecurity/trivy-action from 0.19.0 to 0.20.0"

---

.github/workflows/ci-spring-boot-container-scan.yml

PF-1296 - Standardize output from trivy to be output in the action log

---

.github/workflows/ci-build-publish-image.yml
.github/workflows/ci-docker-build-publish-image.yml
.github/workflows/ci-quarkus-build-publish-image.yml
.github/workflows/ci-spring-boot-build-publish-image.yml
.gitignore

Adding a feature for keyless image-signing with cosign for spring-boot, docker and quarkus-images. 
The feature is by default turned Off

PF-1389 cosign keyless signing

---

.github/workflows/ci-docker-build-publish-image.yml
.github/workflows/ci-quarkus-build-publish-image.yml
.github/workflows/ci-spring-boot-build-publish-image.yml

Should not print the provenance metadata in the summary

PF-1400 Remove provenance output from the signing workflow

---

.github/workflows/ci-docker-build-publish-image.yml
.github/workflows/ci-quarkus-build-publish-image.yml
.github/workflows/ci-spring-boot-build-publish-image.yml

Updating provenance.json with required fields according to the slsaprovenance v1 spec

Pf 1408 use slsaprovenance1 as predictatype

---

.github/workflows/ci-docker-build-publish-image.yml
.github/workflows/ci-quarkus-build-publish-image.yml
.github/workflows/ci-spring-boot-build-publish-image.yml

* Moved `builder.id` to `runDetails.builder.id` 
* Renamed `repository_owner_id` to `repositoryOwnerId`

PF-1421 Updates in the provenance.json file

---

.github/workflows/ci-quarkus-build-publish-image.yml
.github/workflows/ci-quarkus-container-scan.yml

ID-5054: Sett LANG env variabel for native kompilering

ID-5054: Sett LANG env variabel for native kompilering

---

.github/workflows/ci-maven-build-lib.yml
.github/workflows/ci-maven-build.yml

Tillate EUW som pr title prefix.
EUW = eudiw = EU digital identity wallet = nye prosjektteamet ut fra ID-porten teamet.

EUW-4: Tillate EUW som pr title prefix

---

.github/workflows/ci-maven-build-lib.yml

Removing explicit permissions due to failing authentication to maven GH repo

PF-000 - Update ci-maven-build-lib.yml

---

.github/workflows/ci-maven-deploy.yml

Add actions read permission for ci-maven-deploy 
